collections:
  my-collection:
    output: true
paginate: 1
timezone: Europe/Paris

algolia:
  application_id: APPID
  index_name:     INDEXNAME
  files_to_exclude:
    - index.html
    - excluded.html
    - excluded_dir/*.html

# Jekyll 3.0 extracted the secondary features into their own plugins
plugins: 
  - jekyll-paginate

